---
- name: Write kubedns pod file
  template: src=kubedns-rc.yml.j2 dest=/etc/kubernetes/kubedns-rc.yaml
  when: dns_setup

- name: Write kubedns service file
  template: src=kubedns-svc.yml.j2 dest=/etc/kubernetes/kubedns-svc.yaml
  when: dns_setup


- name: Check that the DNS pod exists
  shell: kubectl get rc kube-dns
  register: has_dns_pod
  failed_when: false
  changed_when: false

- name: Create kubedns pod
  shell: kubectl create -f /etc/kubernetes/kubedns-rc.yaml
  when: dns_setup and has_dns_pod.rc != 0

- name: Update DNS replication service
  shell: kubectl update -f /etc/kubernetes/kubedns-rc.yaml
  when: dns_setup and has_dns_pod.rc == 0


- name: Check that the DNS service exists
  shell: kubectl get service kube-dns
  register: has_dns_service
  failed_when: false
  changed_when: false

- name: Create kubedns service
  shell: kubectl create -f /etc/kubernetes/kubedns-svc.yaml
  when: dns_setup and has_dns_service.rc != 0

- name: Update kubedns service
  shell: kubectl update -f /etc/kubernetes/kubedns-svc.yaml
  when: dns_setup and has_dns_service.rc == 0
