---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: etcd
  sudo: yes
  roles:
          - etcd
          - flannel-config

- hosts: masters
  sudo: yes
  roles:  
          - flannel
          - kubernetes
          - master
          - skydns
          - images

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - flannel
          - minion
          - images

# - hosts: masters
#   sudo: yes
#   roles:  
#           - images
#           # - kube-dashboard
        