---
- hosts: all
  sudo: yes
  roles:
          - common

# - hosts: etcd
#   sudo: yes
#   roles:
#           - etcd
#           - flannel-config

# - hosts: masters
#   sudo: yes
#   roles:  
#           - flannel
#           - kubernetes
#           - master

# - hosts: minions
#   sudo: yes
#   roles:
#           - kubernetes
#           - flannel
#           - minion
#           - k8s-images

- hosts: masters
  sudo: yes
  roles:  
          - kube-dns
