---
- name: restart daemons
  command: /bin/true
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler
          - restart docker

- name: restart apiserver
  service: name=kube-apiserver state=restarted

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted

- name: restart scheduler
  service: name=kube-scheduler state=restarted

- name: restart docker
  service: name=docker state=restarted