---
- name: Creates directory
  file: path=/etc/kubernetes/yaml state=directory mode=0775

- name:  copy prometheus
  copy: src=./files/prometheus.yml dest=/etc/kubernetes/yaml/prometheus.yml mode=0755 force=yes

- name: Create prometheus
  shell: kubectl create  -f /etc/kubernetes/yaml/prometheus.yml



