---
- name: Install epel
  yum: name=epel-release state=latest
# - name: start firewalld
#   service: name=firewalld state=started
# - name: build centos7-nginx dockerfile
#   command: firewall-cmd --zone=public --add-port=8080/tcp --permanent

- name: setenforce
  command: setenforce 0

# - name: truncate iptables rule
#   command: /sbin/iptables -P INPUT ACCEPT;/sbin/iptables -F

- name: Stop firewalld
  service: name=firewalld state=stopped

- name: Install iptables
  yum: name=iptables-services state=latest

- name: Start iptables
  service: name=iptables state=started

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: has_iptables
  failed_when: "'package iptables-services is not installed' not in has_iptables.stdout and has_iptables.rc != 0"
  changed_when: false


- name: Set IP address variables
  set_fact:
    master_ip_address: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
    etcd_ip_address: "{{ hostvars[groups['etcd'][0]]['ansible_default_ipv4']['address'] }}"