---
- name: Install epel
  yum: name=epel-release state=latest
- name: build centos7-nginx dockerfile
  command: firewall-cmd --zone=public --add-port=8080/tcp --permanent

# - name: Stop firewalld
#   service: name=firewalld state=stopped

# - name: Install iptables
#   yum: name=iptables-services state=latest

# - name: Start iptables
#   service: name=iptables state=started

# - name: Determine if iptables-services installed
#   command: "rpm -q iptables-services"

- name: Set IP address variables
  set_fact:
    master_ip_address: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
    etcd_ip_address: "{{ hostvars[groups['etcd'][0]]['ansible_default_ipv4']['address'] }}"