---
- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  check_mode: no

- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started

- name: Open apiserver port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT -m comment --comment "kube-apiserver"
  when: iptablesrules.stdout.find("kube-apiserver") == -1

# - name: delete  icmp-host-prohibited  forward with iptables
#   command: /sbin/iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
# # iptables -I FORWARD -s 10.1.0.0/16 -j ACCEPT
# - name: delete  icmp-host-prohibited  input with iptables
#   command: /sbin/iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited

- name: Save iptables rules
  command: service iptables save
  when: iptablesrules.stdout.find("kube-apiserver") == -1
