---
- name: Install kubernetes master from RHEL7 packages
  yum: pkg=kubernetes-master state=latest

- name: Install kubernetes client from RHEL7 packages
  yum: pkg=kubernetes-client state=latest

- name: mkdir kubelet ca from master
  file: path=/etc/kubernetes/ssl state=directory  mode=0755

- name: generate ca
  command: openssl genrsa -out ca.key 2048 chdir=/etc/kubernetes/ssl
- command: openssl req -x509 -new -nodes -key ca.key -subj "/CN=k8s.com" -days 5000 -out ca.crt chdir=/etc/kubernetes/ssl
- command: openssl genrsa -out server.key 2048 chdir=/etc/kubernetes/ssl
- command: openssl req -new -key server.key -subj "/CN=`hostname`" -out server.csr chdir=/etc/kubernetes/ssl
- command: openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 5000 chdir=/etc/kubernetes/ssl

- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler
          - restart docker

- name: write the new style config file for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  notify:
          - restart controller-manager

- name: write the config file for scheduler
  copy: src=scheduler dest=/etc/kubernetes/scheduler
  notify:
          - restart scheduler

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- name: Enable docker
  service: name=docker enabled=yes state=started
  
- include: iptables.yml
  when: has_iptables.rc == 0
