---
- name: Install kubernetes master from RHEL7 packages
  yum: pkg=kubernetes-master state=latest

- name: Install kubernetes client from RHEL7 packages
  yum: pkg=kubernetes-client state=latest

- name: write the ca.sh files
  template: src=ca.sh.j2 dest=/etc/kubernetes/ca.sh  mode=0755

- name: execute ca.sh 
  script: /etc/kubernetes/ca.sh
- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler
          - restart docker

- name: write the new style config file for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  notify:
          - restart controller-manager

- name: write the config file for scheduler
  copy: src=scheduler dest=/etc/kubernetes/scheduler
  notify:
          - restart scheduler

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- name: Enable docker
  service: name=docker enabled=yes state=started
  
- include: iptables.yml
  when: has_iptables.rc == 0
# - include: firewall.yml