---
- name: Install kubernetes master from RHEL7 packages
  yum: pkg=kubernetes-master state=latest

- name: Install kubernetes client from RHEL7 packages
  yum: pkg=kubernetes-client state=latest

- name: mkdir kubelet ca from master
  file: path=/etc/kubernetes/ssl state=directory  mode=0755

- name: write the openssl config file for openssl
  template: src=openssl.cnf.j2 dest=/etc/kubernetes/ssl/openssl.cnf

- name: generate ca
  command: openssl genrsa -out ca-key.pem 2048 chdir=/etc/kubernetes/ssl
- command: openssl req -x509 -new -nodes -key ca-key.pem -days 10000 -out ca.pem -subj "/CN=kube-ca"  chdir=/etc/kubernetes/ssl

- command: openssl genrsa -out apiserver-key.pem 2048 chdir=/etc/kubernetes/ssl
- command: openssl req -new -key apiserver-key.pem -out apiserver.csr -subj "/CN=kube-apiserver" -config openssl.cnf   chdir=/etc/kubernetes/ssl
- command: openssl x509 -req -in apiserver.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out apiserver.pem -days 365 -extensions v3_req -extfile openssl.cnf chdir=/etc/kubernetes/ssl

- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver
          - restart controller-manager
          - restart scheduler
          - restart docker

- name: write the new style config file for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  notify:
          - restart controller-manager

- name: write the config file for scheduler
  copy: src=scheduler dest=/etc/kubernetes/scheduler
  notify:
          - restart scheduler

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- name: Enable docker
  service: name=docker enabled=yes state=started
  
- include: iptables.yml
  when: has_iptables.rc == 0
