---
- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  check_mode: no

- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started

- name: Open kubelet port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 10250 -j ACCEPT -m comment --comment "kubelet"
  when: iptablesrules.stdout.find("kubelet") == -1

# - name: delete  icmp-host-prohibited  forward with iptables
#   command: /sbin/iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited 

# - name: delete  icmp-host-prohibited  input with iptables
#   command: /sbin/iptables -D INPUT -j REJECT --reject-with icmp-host-prohibited


- name: Save iptables rules
  command: service iptables save
  when: iptablesrules.stdout.find("kubelet") == -1
